# Generated by Django 4.1 on 2022-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchitem',
            name='review',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
